<a href="https://colab.research.google.com/github/mfcstt/data_science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list = [0,1,2,3,4,5,6]
array = np.array(list)

In [ ]:
print(type(list))
print(type(array))



<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array[0] = 9
print(array)

[9 1 2 3 4 5 6]


In [ ]:
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
lista_de_notas = [9.8, 5.6, 7.8, 9.2, 6.7]
notas = np.array(lista_de_notas)

In [ ]:
print("Maximo", notas.max())
print("Minimo", notas.min())
print("Desvio Padrão", notas.std())
print("Media", notas.mean())
print("Posição do menor", notas.argmin())

Maximo 9.8
Minimo 5.6
Desvio Padrão 1.5497096502248415
Media 7.82
Posição do menor 1
